# Generated by Django 2.1.3 on 2018-11-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('name', models.CharField(max_length=25)),
                ('link', models.CharField(max_length=200)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
