# Generated by Django 2.1.3 on 2018-11-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liteboardbackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.CharField(max_length=500),
        ),
    ]
